source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NSNotificationCenterMock_Example', :exclusive => true do
  pod "NSNotificationCenterMock", :path => "../"
end

target 'NSNotificationCenterMock_ExampleTests', :exclusive => true do
    pod "Nimble"
    pod "NSNotificationCenterMock", :path => "../"
end

target 'NSNotificationCenterMock_Tests', :exclusive => true do
  pod "NSNotificationCenterMock", :path => "../"

  
end
